### ISSUE TITLE
can't output entrypoints when `chalk` < 5.3.0

### ISSUE THREAD

**Issue by cubxx** [vktrl/bun-plugin-pino#1]
when I install `bun-plugin-pino`, it won't install `chalk`, but I still run it with no console error. because I use it in monorepo, and other package in monorepo have installed low version `chalk`. So `bun-plugin-pino` don't show runtime error but appear output error just like issue title.

maybe `chalk` should be in `dependencies` not `devDependencies`

**Comment by vktrl** [comment]
Thanks for the report!

I just yeeted chalk and added some logging options. Try out version `1.1.0`.

**Comment by cubxx** [comment]
thanks for your working. Unexpectly, I find it maybe not problem of bun-plugin-pino, but bun 
https://github.com/oven-sh/bun/issues/13445#issue-2477746910

**Comment by vktrl** [comment]
> thanks for your working. Unexpectly, I find it maybe not problem of bun-plugin-pino, but bun [oven-sh/bun#13445 (comment)](https://github.com/oven-sh/bun/issues/13445#issue-2477746910)

Not installing dev dependencies of dev dependencies should be the correct behavior. Either way, issues with module resolution and dependency management are why this package exists in the first place, and library authors adding deps instead of a couple of lines of code are not helping.
